### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by Jothish21** [INFO526-DataViz/project-final-Infographic-Innovators#6]
The following is the peer review of the Presentation proposal by Visual Virtuosos. The team members that participated in this review are 

- Jothish Kumar Polaki - @Jothish21
- Partha Koundinya P - @partha-pkp
- Kashyap Sai Prasad Nadendla - @KashyapNadendla
- Harshit Mehra - @harshitmehra1

- Content: Is the research question well designed and is the data being used relevant to the research question?
    - Yes, the questions are well designed and the data is relevant to the questions.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?
    - Team has created good and appropriate visualizations and the plots are interpreted accurately.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?
    - The project is thoroughly planned out and implemented accordingly, the limitations are also carefully considered.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
    - The slides are well organized, are readable, and has sufficient text. All the plots are labelled and legends are relevant.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?
    - The presentation is great and they deserve marks for the way they presented, it appeared to be well practiced. It did not feel like scripted, and everyone has a good contribution in the project.

**Comment by bharath03-a** [comment]
Thanks for the review!

Team Infographic Innovators
