### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by AthiraThekkemadathilAnilkumar** [INFO526-DataViz/project-final-Infographic-Innovators#7]
The following is the peer review of the Presentation proposal by Plot Pioneers. The team members that participated in this review are 

* Athira Thekkemadathil Anilkumar - @AthiraThekkemadathilAnilkumar 
* Shalon Walter - @shalonwalter 
* Priyarsha Vallabhaneni - @Priyarsha31 
* Chethana Thondebhavi Shantha Kumar - @Chethana-16 

- Content: Is the research question well designed and is the data being used relevant to the research question?
             Yes, the research question is well designed and the data is relevant to the question. 

- Content: Did the team use appropriate visualizations and did they interpret them accurately?
         Yes, they have used appropriate visualizations and they interpreted them correctly.  

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?
      Yes, the project is carefully planned and they even well discussed about the limitations. We did find the project to be quite interesting and intriguing. The visualizations were also more refined which means they did put in a quality amount of time and effort in the project.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
       Yes, the slides were well-organized, with readable text provided in sufficient quantity. All the plots were appropriately labeled and relevant to the content.

Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?
        They presented well and seemed thoroughly prepared, without sounding scripted. Each person had an equal opportunity during the presentation.

**Comment by bharath03-a** [comment]
Thanks for the review!

Team Infographic Innovators
